[project]
name = "shared"
version = "0.1.0"
description = "IDs, fingerprints, and helpers"
requires-python = ">=3.11"
dependencies = [
  "orjson>=3.9.7",
  "python-dateutil>=2.9.0",
  "six>=1.16.0",
  "core_utils",
]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where  = ["src"]
include = ["shared*"]
