[project]
name = "core_models"
version = "0.1.0"
description = "Shared pydantic models and schemas"
requires-python = ">=3.11"
dependencies = [
  "pydantic>=2.7.0",
  "core_utils",
]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where  = ["src"]
include = ["core_models*"]

[tool.setuptools.package-data]
core_models = ["schemas/*.json"]
