[project]
name = "core_config"
version = "0.1.0"
description = "Shared config for BatVault"
requires-python = ">=3.11"
dependencies = ["pydantic>=2.7.0", "pydantic-settings>=2.3.0"]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where  = ["src"]
include = ["core_config*"]
