[project]
name = "core_utils"
version = "0.1.0"
description = "IDs, fingerprints, and helpers"
requires-python = ">=3.11"
dependencies = [
    "orjson>=3.9.7",
    "fastapi>=0.112.0",
    "core_config"
]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where  = ["src"]
include = ["core_utils*"]
